org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neoforge_version=21.1.247
neoforge_version_range=[21.1.247,)
parchment_minecraft=1.21
parchment_version=2024.11.10

mod_id=rocketengine
mod_name=Rocket Engine Plan
mod_version=0.6.0
mod_group_id=com.jia6261.rocketengine
mod_license=All Rights Reserved
mod_authors=jia6261
mod_description=Lava-powered redstone rocket engine, RCS and spacecraft utilities using Sable physics.

sable_version_range=[2.0.0,3.0.0)
sable_modrinth_version=U678xqle
